version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app       # Mount the current directory to /app in the container
      - /app/node_modules  # Prevent overwriting node_modules with host files
    command: npm run lint
