import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Laz Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-arboriabook antialiased bg-slate-950 text-white`}
      >
        {children}
      </body>
    </html>
  );
}
