import type { Metadata } from "next";
import "./globals.css";
import ColorProvider from "./colorProvider";

export const metadata: Metadata = {
	title: "Laz's Portfolio",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ColorProvider>
			<html lang="en">
				<body
					className={`font-arboriabook antialiased bg-slate-950 text-white`}
				>
					{typeof window === "undefined" ? children : (<div></div>)}
				</body>
			</html>
		</ColorProvider>
	);
}
